version: '3.8'

services:
  nova-server-openresty:
    image: openresty/openresty:alpine
    container_name: nova-server-openresty
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ../src:/usr/local/openresty/waf:ro
      - ../logs:/usr/local/openresty/nginx/logs/
    environment:
      - TZ=Asia/Shanghai # 设置时区
    restart: always
